dist: focal
os: linux
cache:
  directories:
  - $HOME/cache

jobs:
  include: 
    - &docker-build
      name: Docker build (Alpine) on amd64
      arch: amd64
      env: DIST=alpine
      install: skip
      script:
      - |
        cat $HOME/cache/test.txt
        echo "$DIST" >> $HOME/cache/test.txt
        cat $HOME/cache/test.txt 
    - <<: *docker-build
      name: Docker build (ubi8) on amd64
      arch: amd64
      env: DIST=ubi8
    #happy-path
    - &happy-path
      name: happy-path (alpine, next)
      install: skip
      env:
        - DIST=alpine
        - CHECTL_CHANNEL=next
        - MINIKUBE_VERSION=v1.18.1
      arch: amd64
      script: cat $HOME/cache/test.txt 
    - <<: *happy-path
      name: happy-path (alpine, stable)
      env:
        - DIST=alpine
        - CHECTL_CHANNEL=stable
        - MINIKUBE_VERSION=v1.18.1
    - <<: *happy-path
      name: happy-path (ubi8, next)
      env:
      - DIST=ubi8
      - CHECTL_CHANNEL=next
      - MINIKUBE_VERSION=v1.18.1
    - <<: *happy-path
      name: happy-path (ubi8, stable)
      env:
      - DIST=ubi8
      - CHECTL_CHANNEL=stable
      - MINIKUBE_VERSION=v1.18.1
