dist: focal
os: linux

env:
  global:
    - MINIKUBE_VERSION=v1.18.1

cache:
  directories:
  - $HOME/cache

jobs:
  include: 
    - &docker-build
      stage: Build images
      name: Docker build (Alpine) on amd64
      arch: amd64
      env: DIST=alpine CHECTL_CHANNEL=next
      install: skip
      script:
      - |
        cat $HOME/cache/test.txt
        echo "$DIST" >> $HOME/cache/test.txt
        cat $HOME/cache/test.txt 
    - <<: *docker-build
      name: Docker build (Alpine) on amd64
      arch: amd64
      env: DIST=alpine CHECTL_CHANNEL=stable
    - <<: *docker-build
      name: Docker build (ubi8) on amd64
      arch: amd64
      env: DIST=ubi8 CHECTL_CHANNEL=next
    - <<: *docker-build
      name: Docker build (ubi8) on amd64
      arch: amd64
      env: DIST=ubi8 CHECTL_CHANNEL=stable
    #happy-path
    - &happy-path
      stage: Run tests
      name: happy-path (alpine, next)
      install: skip
      env:
        - DIST=alpine CHECTL_CHANNEL=next
      arch: amd64
      script: cat $HOME/cache/test.txt 
    - <<: *happy-path
      name: happy-path (alpine, stable)
      env:
        - DIST=alpine CHECTL_CHANNEL=stable
    - <<: *happy-path
      name: happy-path (ubi8, next)
      env: DIST=ubi8 CHECTL_CHANNEL=next
    - <<: *happy-path
      name: happy-path (ubi8, stable)
      env: DIST=ubi8 CHECTL_CHANNEL=stable
